version: '3.3'

services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_USER: mood
      MYSQL_PASSWORD: mood
      MYSQL_DATABASE: ts-mood-logs
    ports:
      - '3306:3306'
    volumes:
      - ts-mood-logs:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  ts-mood-logs: {}
